//
//  UILabel+Night.h
//  UILabel+Night
//
//  Copyright (c) 2015 Draveness. All rights reserved.
//
//  These files are generated by ruby script, if you want to modify code
//  in this file, you are supposed to update the ruby code, run it and 
//  test it. And finally open a pull request.

#import <UIKit/UIKit.h>
#import "NSObject+Night.h"

IB_DESIGNABLE

@interface UILabel (Night)

@property (nonatomic, copy, setter = dk_setTextColorPicker:) DKColorPicker dk_textColorPicker;
@property (nonatomic, copy, setter = dk_setShadowColorPicker:) DKColorPicker dk_shadowColorPicker;
@property (nonatomic, copy, setter = dk_setHighlightedTextColorPicker:) DKColorPicker dk_highlightedTextColorPicker;

@property (nonatomic, copy) IBInspectable NSString *wade_textColorPicker;
@property (nonatomic, copy) IBInspectable NSString *wade_shadowColorPicker;
@property (nonatomic, copy) IBInspectable NSString *wade_highlightedTextColorPicker;

@end
